title: rohan vijay prasad
# site settings
taglong: wandering since 2000 # goes beneath title
# tagshort: rohan's website
baseurl: ""
url: https://piazzai.github.io/cvless

description: the blog of rohan prasad


theme: cvless



# author settings
author: 
  name: Rohan Prasad
  email: username@domain.com
photo: assets/files/photo.jpg
# address: Foobar Hall 1.23
# phone: +1 234 567 890

# social media links
social:
  #facebook: username
  github: tohab
  #instagram: username
  linkedin: therohanprasad
  #stackoverflow: 0000000/username
  x: shoelesstohab

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
