title: rohan prasad
# site settings
# taglong:  # goes beneath title
tagshort: an exploration
baseurl: ""
url: tohab.github.io

description: the blog of rohan prasad

plugins:
- jekyll-remote-theme
remote_theme: pages-themes/primer

# author settings
author: 
  name: Rohan Prasad
  email: username@domain.com
photo: assets/files/photo.jpg
# address: Foobar Hall 1.23
# phone: +1 234 567 890

# social media links
social:
  #facebook: username
  github: tohab
  #instagram: username
  linkedin: therohanprasad
  #stackoverflow: 0000000/username
  x: shoelesstohab

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
