name: Deploy site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true    # caches gems between runs

      - name: Configure Bundler
        run: |
          bundle config path vendor/bundle
          bundle config deployment true

      - name: Install Ruby gems
        run: bundle install --jobs=4 --retry=3

      - name: Verify Jekyll
        run: |
          bundle show jekyll || echo "jekyll not in Gemfile"
          bundle exec jekyll -v

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Build site with Jekyll
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace

      - name: Setup Node (for PurgeCSS)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Purge unused CSS
        run: |
          npm ci
          npm install -g purgecss
          purgecss -c purgecss.config.js || echo "skip purgecss if not applicable"

      - name: Deploy to gh-pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
